### PR TITLE
Fixed #8

### LINKED ISSUE #8: Search Illust without login doesn't work anymore?
- version:
- `node` version: v9.8.0
- `npm` (or `yarn`) version: 5.6.0

**Do you want to request a _feature_ or report a _bug_?:**
_Bug_ also probably _features_ to change example documentation and error message
**What is the current behavior?:**
constructor without username & password arguments should be working, since on documentation said that. But, it got ```TypeError: Expected a string, got undefined```

**Example**
```
const pixiv = new Pixiv(); // TypeError: Expected a string, got undefined
  pixiv.searchIllust('艦これ10000users入り')
    .then((json) => {
      console.log(json);
    }).catch((err) => {
      console.log(err);
    });
```

**Suggested solution:**
I know, this is due of API behavior, (Refer to commit message) : 
https://github.com/upbit/pixivpy/commit/7bd8e23b0f92aaaf1c168b7efdd2af8cf2de133c

Feature request : 
- [x] Change Error message : `Auth is required. Expected a string, got ${typeof this.username}`
- [x] Update example documentation

### PR DESCRIPTION
**Pull request by adefirmanf**
Refer to issue #8 

**Another issue found**:
* [x] Do not reference the index file directly (unicorn/import-index). 
* [x] `lint-staged` no longer supports running scripts defined in package.json.

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by adefirmanf** [comment]
Username & Password Environment in travis.ci should be check.

**Comment by akameco** [comment]
@adefirmanf Opps! Sorry. I fixed travis config.

**Comment by akameco** [comment]
And, add to contributors table 👍 

```
yarn run add-contributor adefirmanf code
```

**Comment by adefirmanf** [comment]
Oops, sorry about `package-lock.json`. I don't realize about `yarn.lock` file. Should I add `package-lock.json` to `.gitignore` ?

**Comment by akameco** [comment]
No. you don't need to.

LGTM 🎉
Thank you!

**Pull request merged**
